# Generated by Django 5.0.7 on 2024-08-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_details_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='num',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='details',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
