# Generated by Django 5.0.7 on 2024-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_rename_num_details_number_alter_details_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='number',
            field=models.CharField(max_length=10),
        ),
    ]
